bekia/bekia/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index, profile, about,safety,terms

from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from .views import index, profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('profile/', profile , name='profile'),
    path('about/', about , name='about'),
    path('safety/', safety , name='safety'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('auth/', include('djoser.urls')),
    # path('auth/jwt', include('djoser.urls.jwt')),
    # path('auth/token', include('djoser.urls.authtoken')),
    path('terms/', terms , name='terms'),
    path('', include('accounts.urls')),
    path('', include('search.urls')),
    path('', include('contact.urls')),
    path('advertise/', include('advertise.urls')),
    # path('', include('search.urls')),
#     path('add_new_ad/', include('advertise.urls')),
]


if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bekia/search/urls.py
from django.urls import path, include
from .views import search
app_name="search"
urlpatterns= [
	path('search', search, name='search_view'),
	
	]

bekia/templates/base/ad.html
   {% load static %}
   <!-- Advertize banner -->
  <a href="/contact"><img class="img-responsive sm-12 rounded mx-auto d-block" src="{% static 'img/ad.jpg' %}"></img>
   </a>
   <!-- end of advertize -->

bekia/templates/base/footer.html
<!-- Footer -->
<footer class="page-footer font-small special-color-dark pt-4">

  <div style="background-color: #E8E7E7">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0">Get connected with us on social networks!</h6>
        </div>
        <!-- Grid column -->

      <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a href="/" class="btn-floating btn-fb mx-1">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a href="/" class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a  href="/"class="btn-floating btn-gplus mx-1">
          <i class="fab fa-google-plus-g"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a href="/" class="btn-floating btn-li mx-1">
          <i class="fab fa-linkedin-in"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a href="/" class="btn-floating btn-dribbble mx-1">
          <i class="fab fa-dribbble"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->


      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3 dark-grey-text">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold">Bekia</h6>
        <p>Bekia is the best local classifieds in Egypt to buy and sell anything you can think of; your old mobile phone, your used sofa, your car, or even your flat. It might even help you find a new job!


Looking to sell something? Bekia is the easiest and fastest way to post a free Ad.</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <a class="dark-grey-text" href="{%url 'about' %}">About Us</a>
        <p>
          <a class="dark-grey-text" href="{% url 'safety' %}">Safety Rules</a>
        </p>
        <p>
          <a class="dark-grey-text" href="{% url 'terms' %}">Terms Of Use</a>
      

      </div>
     
      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Contact</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> info@example.com</p>
        <p>
          <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
        <p>
          <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center text-black-50 py-3">© 2019 Copyright:
    <a class="dark-grey-text" href="https://mdbootstrap.com/education/bootstrap/"> Bekia.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

bekia/templates/base/navbar.html
<nav class="navbar fixed navbar-light bg-info">
  <form action="{% url 'search:search_view' %}" class="form-inline">
    <input value="{{ request.GET.q }}" class="form-control mr-sm-2" style="min-width: 40%" type="search" placeholder=" Search for your item here" name="q" aria-label="Search">
     <input value="{{ request.GET.p }}" class="form-control mr-sm-2" style="min-width: 40%" type="search" placeholder=" Search by location here" name="p" aria-label="Search">
    <button style="float: right;" class="btn btn-outline-light text-dark  my-2 my-sm-0 custom-button-width text-right" type="submit"><i class="fa fa-search"></i>Search</button>
  </form>
</nav>

<!-- categories table -->
  <form action="" method="get">
        
<div class="table-responsive">
<table class="table table-borderless">
  <thead>
    <tr>
      <th scope="col"><a href="/?q=Vehicles"><img src="https://img.icons8.com/color/48/000000/fiat-500.png">Vehicles</a></th>
      <th scope="col"><a href="?q=Properties"><img src="https://img.icons8.com/color/48/000000/add-property-1.png">Properties</a></th>
      <th scope="col"><a href="/?q=MobilePhones&Accessories"><img src="https://img.icons8.com/color/48/000000/two-smartphones.png">Mobile Phones & Accessories</a></th>
      <th scope="row"><a href="/?q=Electronics&HomeAppliances"><img src="https://img.icons8.com/color/48/000000/tv.png">Electronics & Home Appliances</a></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><a href="/?q=Home&Garden"><img src="https://img.icons8.com/color/48/000000/armchair.png">Home & Garden</a></th>
      <th scope="row"><a href="/?q=Fashion"><img style="max-height:2em;"src="https://img.icons8.com/color/48/000000/green-dress.png">Fashion & Beauty</a></th>
      <th><a href="/?q=Pets"><img style="max-height:2em;"src="https://img.icons8.com/color/48/000000/sloth.png">Pets</a></td>
      <th><a href="/?q=Kids&Babies"><img style="max-height:2em;" src="https://img.icons8.com/color/48/000000/baby-feet.png">Kids & Babies</a></th>
    </tr>
    <tr>
      <th scope="row"><a href="/?q=SportingGoods&Bikes"><img style="max-height:2em;" src="https://img.icons8.com/color/48/000000/cycling-road.png">Sporting Goods & Bikes</a></td>
      <th><a href="/?q=Hobbies,Music,Art & Books"><img style="max-height:2em;" src="https://img.icons8.com/color/48/000000/musical-notes.png">Hobbies,Music,Art & Books</a></th>
      <th><a href="/?q=Jobs"><img style="max-height:2em;"src="https://img.icons8.com/color/48/000000/find-matching-job.png">Jobs</a></th>
      <th><a href="/?q=Business&Industrial"><img style="max-height:2em;"src="https://img.icons8.com/color/48/000000/company.png">Business & Industrial</a></th>
    </tr>
    <tr>
      <th scope="row"><a href="/?q=services"><img style="max-height:2em;" class="rounded-circle"  src="https://img.icons8.com/color/48/000000/support.png">services</a></th>
      
  </tbody></form>
 
</table>
</div>