bekia/advertise/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter
from .views import (AdCreate,
					AdDetailView,
					AdUpdateView,
					AdDeleteView,
					category_list,
					# Ad_list,ad_detail,
					# AdListAPI,
					#  AdDetailAPI,
					AdListGeneric,
					AdDetailgeneric,
					UserList,
					UserDetail,
					# api_root,
					# AdViewSet,
					# UserViewSet
					)


app_name="advertise"


urlpatterns= [
	path('new', AdCreate.as_view(), name='create'),
	path('<pk>/detail', AdDetailView.as_view(), name='advertise-detail'),
	path('<pk>/update', AdUpdateView.as_view(), name='advertise-update'),
    path('<pk>/delete', AdDeleteView.as_view(), name='advertise-delete'),
    path('category/', category_list, name='category'),
    #API_URLS:
    # path('list/', Ad_list, name='ad_list'),
    # path('<int:pk>/', ad_detail, name='ad_detail'),
    # path('', include(router.urls)),
    # path('api/', api_root),
    path('listview/', AdListGeneric.as_view(), name ='ad-list'),
    path('detailview/<int:pk>',AdDetailgeneric.as_view(), name ='ad_detailview'),
    path('users/', UserList.as_view(), name ='user-list'),
	path('users/<int:pk>/', UserDetail.as_view(),name ='user-detail'),
	path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
  ]
urlpatterns = format_suffix_patterns(urlpatterns)

bekia/bekia/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index, profile, about,safety,terms

from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from .views import index, profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('profile/', profile , name='profile'),
    path('about/', about , name='about'),
    path('safety/', safety , name='safety'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('auth/', include('djoser.urls')),
    # path('auth/jwt', include('djoser.urls.jwt')),
    # path('auth/token', include('djoser.urls.authtoken')),
    path('terms/', terms , name='terms'),
    path('', include('accounts.urls')),
    path('', include('search.urls')),
    path('', include('contact.urls')),
    path('advertise/', include('advertise.urls')),
    # path('', include('search.urls')),
#     path('add_new_ad/', include('advertise.urls')),
]


if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bekia/contact/urls.py
from django.urls import path, include

from .views import contact_us
app_name= "contact"

urlpatterns= [
	path('contact/', contact_us , name='contact'),
	]

bekia/contact/models.py
from django.db import models


class ContactUs(models.Model):
	name 	= models.CharField(max_length=120, null=True, blank=True)
	email 	= models.EmailField(null=True, blank=True)
	subject = models.CharField(max_length=120,null=True, blank=True)
	message = models.TextField(max_length=300,null=True, blank=True)
	

	def __str__(self):
		return self.name


	class Meta:
		verbose_name_plural = "contact us"

bekia/contact/forms.py
from django import forms

from .models import ContactUs
class ContactForm(forms.ModelForm):
	class Meta:
		model = ContactUs
		fields = ['name', 'email', 'subject', 'message']

bekia/contact/views.py
from django.shortcuts import render,redirect
from .forms import ContactForm
from django.contrib import messages
# Create your views here.
def contact_us(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, f'Your message was sent succesfully')
			return redirect('/')
	else:
		form = ContactForm()
		messages.error(request, f'please Enter Correct values')
	context = {'form':form}
	return render(request, 'contact.html', context)

bekia/templates/about.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<p class="mx-auto">
	Who are Bekia Group?
We’re a global product and tech group. +20 brands. 5000 people. One mindset.

 

We empower people to upgrade their lives. Our products & services make it super easy for anyone to buy or sell almost anything.

 

Every month 350 million people use our market-leading trading platforms such as Avito, letgo, dubizzle, OLX and a dozen other local brands. We’re going for a billion.</p>

{% endblock %}

bekia/templates/ad.html
   {% load static %}
   <!-- Advertize banner -->
  <a href="/contact"><img class="rounded mx-auto d-block" src="{% static 'img/ad.jpg' %}"></img>
   </a>
   <!-- end of advertize -->

bekia/templates/base.html
{% load static %}
 <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
       <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
       <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!-- fontawsome CDN -->
       <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </head>

<body class="fluid">
    	{% include 'base/ad.html' %}
    	<!-- first nav -->
	<div class="container">
	  <div class="row">
	  		<div class="col-md-6">
	        <a href="{% url 'index'%}"><img class="p-2" src="{% static 'img/logo.png' %}" style=" width: 200px; height: 200px; " ></img></a>
			   
	        </div>
	        <div class="col-md-6 text-right" style="margin-top: 5em;">
	    		<a href="{% url 'contact:contact'%}" type="button" class="btn btn-light custom-button-width .navbar-right">Help &amp; Contact</a>
	    		{% if user.is_authenticated %}
				<a type="button" href="{% url 'profile' %}"class="btn btn-outline-primary custom-button-width .navbar-right"><i class="fas fa-user-alt"></i>  My Account</a>
				<a type="button" href="{% url 'advertise:create' %}"class="btn btn-success custom-button-width .navbar-right"><i class="fas fa-plus"></i> place an Ad</a>
				{% else %}
				<a type="button" href="{% url 'auth_login' %}"class="btn btn-outline-primary custom-button-width .navbar-right"><i class="fas fa-user-alt"></i> Login</a>
				<a type="button" href="{% url 'registration_register' %}"class="btn btn-success custom-button-width .navbar-right"><i class="fas fa-plus"></i> Register</a>
				{% endif %}
	    	</div>
	  </div>
	</div>


   <div class="fluid" style="background-color: #F2F3F4;">

			<div class="container mx-auto sm-col-12">
    			{% include 'base/navbar.html' %}
			</div>
	</div>

	<div class="container">

    	{% block content %}
    	{% endblock %}
    </div>

   </div>
<!-- footer -->

		<div class="container">
			<hr>
		{% include 'base/footer.html' %}
		</div>
<!-- javascript CDN -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
  </html>

bekia/templates/contact.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
{% if messages %}
<ul>
    {% for message in messages %}
       <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="submit" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>
{% endblock %}

bekia/templates/index.html
{% extends "base.html" %}
{% block content %}
	
		<div class="row">

	{% for obj in qs %}
	<div class="col">
		
		<div class="card" style="width: 18rem;">
	
	<a href="{{ obj.get_absolute_url}}">
  	<img src="{{ obj.image.url}}" class="card-img-top" alt="{{ obj.title}} logo"  >
  	</a>

  <div class="card-body">
    <h5 class="card-title">{{ obj.title }}</h5>
    <p class="card-text">{{ obj.description|truncatewords:12 }}.</p>
     <p class="card-text">{{ obj.price }} &#163;</p>
    <a href="{{ obj.get_absolute_url}}" class="btn btn-primary">View</a> <!-- same as next -->
  </div>
</div>
		{% if forloop.counter|divisibleby:3 %}
	  	 </div></div>
	  	 <div class="row"><div class="col-12"><hr></div>
	   {%  else %}
           </div>
	   {% endif %}
	   
	
	{% endfor %}
</div>

{% endblock %}

bekia/templates/profile.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content%}
{% if messages %}
<ul>
    {% for message in messages %}
       <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="container">
<div class="content-section">
  
    <div class="media-body">
      <h2 class="account-heading">{{user.username}}</h2>
      <p class="text-secondary">{{user.email}}</p>
    </div>
</div>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Profile info</legend>

      {{ user_update.as_p }}
      
      <div class="form-group">
      <button class="btn btn-outline-info" type="submit">
        Update
      </button>
      </div>
  </form>
</div>
	{% endblock %}

bekia/templates/safety.html
{% extends 'base.html' %}
{% block content %}

<p><ul><h3>How to safely sell?</h3>
<li>Make sure to inform the buyer of any defects in the item you are selling.</li>
<li>Use only simple payment methods that you trust and are familiar with, especially cash payments
In any case, do not send copies of your documents, personal data and most importantly financial information</li>
<li>Don’t deal with buyers who keep on constantly changing the meeting place or calling from different mobile numbers.</li>
<li>If you see the buyer waiting for you in his car and he wants to check the item, ask him kindly to get out of the car to check it outside; it is always better in a public place you have both chosen.</li>
</ul></p>
{% endblock %}

bekia/templates/terms.html
{% extends 'base.html' %}
{% block content %}
<h3> ACCEPTANCE</h3>
<p>
Bekia Egypt LLC, a limited liability company 5th settlement, New Cairo, Egypt and their affiliates and / or branches (hereinafter together "Bekia") provide a collection of online resources which include classified advertisements and forums (collectively, the "Service") on the website bekia.com.eg, related sites and the mobile application of the platform (collectively, the "Website").

The Website and the Service are provided to you subject to these bekiaTerms of Use (these "Terms"). For the purpose of the Terms and wherever the context so requires, the terms 'you' and “your” shall mean any person who uses the Website or the Service in any manner whatsoever including persons browsing the Website and its content, posting comments or any content or responding to any advertisements or content on the Website. By accessing, browsing or using the Website or Service, you agree to comply with these Terms. Additionally, when using a portion of the Service, you agree to conform to any applicable posted guidelines for such Service, which may change or be updated from time to time at bekia sole discretion. You understand and agree that you are solely responsible for reviewing these Terms from time to time. Should you object to any term or condition of these Terms, any guideline, or any subsequent changes thereto or become unhappy with Bekia or the Service in any way, your only choice is to immediately discontinue use of the bekia Website. These Terms may be updated by Bekia at any time at its sole discretion. bekia may send you notices of changes to the Website or the Terms pursuant to Section xxi (I) herein. OLX may provide a translation of the English version of the Terms into other languages. You understand and agree that any translation of the Terms into other languages is for your convenience only and that the English version governs the terms of your relationship with bekia. Furthermore, if there are any inconsistencies between the English version of the Terms and any translation, the English version of the Terms shall govern.</p>
{% endblock %}